// Day 4 with input set bundled in the executable

#include <conio.h>
#include <cbm.h>
#include <time.h>

#include "day05_data.h" // generated by elves

#define POP(from) p1stacks[from][p1top[from]--]
#define PUSH(to, v) p1stacks[to][++p1top[to]] = v

void dump(unsigned char stacks[NR_STACKS][50], unsigned char top[NR_STACKS]);

void main(void) {
    unsigned char x,y;
    clock_t t0, t1;
    unsigned int i, j;
    //unsigned char (*p)[50];
    //unsigned char (*q)[50];
    //unsigned char *q, *p;
    unsigned char from,to;

    t0 = clock();
    screensize(&x, &y);
    if (x == 80) fast();

    /*
    for (i = 0; i < NR_STACKS; i++) {
        for (j = 0; j <= top[i]; j++) {
            cputc(stacks[i][j]);
        }
        cprintf("\r\n");
    }

    for (i = 0; i < nr_moves; i++) {
        cprintf("Move %d from %d to %d\r\n", moves.nr[i], moves.from[i]+1, moves.to[i]+1);
    }
    */

    for (i = 0; i < nr_moves; ++i) {
        // part1
        for (j = 0; j < moves.nr[i]; ++j) {
            PUSH(moves.to[i], POP(moves.from[i]));
        }

        // part2
        /*
        p = (unsigned char *)&(p2stacks[moves.from[i]]) + p2top[moves.from[i]];
        q = (unsigned char *)&(p2stacks[moves.to[i]]) + p2top[moves.to[i]] + moves.nr[i];
        for (j = 0; j < moves.nr[i]; ++j) {
            *q-- = *p--;
        }
        p2top[moves.from[i]] -= moves.nr[i];
        p2top[moves.to[i]] += moves.nr[i];
        */
        //t = p2top[moves.to[i]] + moves.nr[i];

        /*
        from = moves.from[i];
        to = moves.to[i];
        p2top[to] += moves.nr[i];
        dump(p2stacks, p2top);
        for (j = 0; j < moves.nr[i]; ++j) {
            p2stacks[to][p2top[to]-j] = p2stacks[from][p2top[from]--];
            dump(p2stacks, p2top);
        }
        */
    }

    cprintf("Part 1\r\n");
    dump(p1stacks, p1top);

    /*
    cprintf("\r\nPart 2\r\n");
    dump(p2stacks, p2top);
    */

    t1 = clock();
    cprintf("Runtime: %ld\n", t1-t0);
}

void dump(unsigned char stacks[NR_STACKS][50], unsigned char top[NR_STACKS]) {
    unsigned char i;
    for (i = 0; i < NR_STACKS; ++i) {
        cprintf("%c", stacks[i][top[i]]);
    }
    cprintf("\r\n");
}

/*
unsigned char pop(const unsigned char from) {
    return stacks[from][top[from]--];
}

void push(const unsigned char to, unsigned char v) {
    stacks[to][++top[to]] = v;
}
*/
