// Day 4 with input set bundled in the executable
//
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <conio.h>
#include <cbm.h>
#include <fcntl.h>
#include <peekpoke.h>
#include <device.h>
#include <time.h>


#include "d4b_data.h" // generated by elves

void solve();

void main(void) {
    unsigned char x,y;
    clock_t t0, t1;

    screensize(&x, &y);

    //cprintf("Start: DEV: %d  screen: %dx%d\r\n", dev, x,y);
    if (x == 80) fast();

    t0 = clock();
    solve();
    t1 = clock();
    cprintf("Runtime: %ld\n", t1-t0);
}

void solve(void) {
    unsigned int nr_contain = 0;
    unsigned int nr_overlap = 0;
    int i;

    for (i = 0; i < assn.nr; i++) {
        // part1 -- does one contain the other?
        if (   (assn.min1[i] <= assn.min2[i] && assn.max1[i] >= assn.max2[i])
            || (assn.min2[i] <= assn.min1[i] && assn.max2[i] >= assn.max1[i]) ) { 
            //cputs("*");
            nr_contain++;

            // if one contains the other, they also overlap (part 2)
            nr_overlap++;

        } else if (   (assn.min1[i] <= assn.max2[i] && assn.max1[i] >= assn.min2[i])
                   || (assn.min2[i] <= assn.max1[i] && assn.max2[i] >= assn.min1[i]) ) {
            // part2 -- does one overlap the other?
            nr_overlap++;
            //cputs("+");
        }
        //cprintf("\r\n");
    }
    cprintf("Part1: %d\r\n", nr_contain);
    cprintf("Part2: %d\r\n", nr_overlap);
}
